export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/auth/reset-password",
  verifyEmail: "/verify-email",
  onboarding: "/onboarding",
  unauthorized: "/unauthorized",
  sessionExpired: "/session-expired",
  dashboard: "/dashboard",
  typingPractice: "/practice",
  codingPractice: "/practice/code/dashboard",
  analytics: "/analytics",
  aiCoach: "/ai-coach",
  aiCoachInsights: "/ai-coach/insights",
  aiCoachPlanner: "/ai-coach/planner",
  aiCoachReports: "/ai-coach/reports",
  aiCoachSettings: "/ai-coach/settings",
  aiCoachGenerator: "/ai-coach/generator",
  settings: "/settings",
  profile: "/profile",
  achievements: "/achievements",
  challenges: "/challenges",
  leaderboards: "/leaderboards",
  friends: "/friends",
  help: "/help",
} as const;
