export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          username: string | null;
          avatar_url: string | null;
          country: string | null;
          preferred_language: string;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          username?: string | null;
          avatar_url?: string | null;
          country?: string | null;
          preferred_language?: string;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          username?: string | null;
          avatar_url?: string | null;
          country?: string | null;
          preferred_language?: string;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_preferences: {
        Row: {
          user_id: string;
          theme: "light" | "dark" | "system";
          keyboard_layout: string;
          daily_goal_minutes: number;
          ai_enabled: boolean;
          typing_experience: "beginner" | "intermediate" | "advanced";
          programming_experience: "none" | "beginner" | "intermediate" | "advanced";
          sound_enabled: boolean;
          haptic_enabled: boolean;
          show_wpm_live: boolean;
          show_accuracy_live: boolean;
          notification_email: boolean;
          notification_push: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          theme?: "light" | "dark" | "system";
          keyboard_layout?: string;
          daily_goal_minutes?: number;
          ai_enabled?: boolean;
          typing_experience?: "beginner" | "intermediate" | "advanced";
          programming_experience?: "none" | "beginner" | "intermediate" | "advanced";
          sound_enabled?: boolean;
          haptic_enabled?: boolean;
          show_wpm_live?: boolean;
          show_accuracy_live?: boolean;
          notification_email?: boolean;
          notification_push?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          theme?: "light" | "dark" | "system";
          keyboard_layout?: string;
          daily_goal_minutes?: number;
          ai_enabled?: boolean;
          typing_experience?: "beginner" | "intermediate" | "advanced";
          programming_experience?: "none" | "beginner" | "intermediate" | "advanced";
          sound_enabled?: boolean;
          haptic_enabled?: boolean;
          show_wpm_live?: boolean;
          show_accuracy_live?: boolean;
          notification_email?: boolean;
          notification_push?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_statistics: {
        Row: {
          user_id: string;
          total_practice_time: number;
          total_sessions: number;
          current_streak: number;
          longest_streak: number;
          last_practice_date: string | null;
          average_wpm: number | null;
          average_accuracy: number | null;
          best_wpm: number | null;
          best_accuracy: number | null;
          total_words_typed: number;
          total_errors: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          total_practice_time?: number;
          total_sessions?: number;
          current_streak?: number;
          longest_streak?: number;
          last_practice_date?: string | null;
          average_wpm?: number | null;
          average_accuracy?: number | null;
          best_wpm?: number | null;
          best_accuracy?: number | null;
          total_words_typed?: number;
          total_errors?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          total_practice_time?: number;
          total_sessions?: number;
          current_streak?: number;
          longest_streak?: number;
          last_practice_date?: string | null;
          average_wpm?: number | null;
          average_accuracy?: number | null;
          best_wpm?: number | null;
          best_accuracy?: number | null;
          total_words_typed?: number;
          total_errors?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      typing_sessions: {
        Row: {
          id: string;
          user_id: string;
          practice_mode: string;
          duration: number;
          final_wpm: number;
          final_accuracy: number;
          consistency: number;
          peak_wpm: number;
          average_wpm: number;
          raw_wpm: number;
          correct_chars: number;
          incorrect_chars: number;
          total_chars: number;
          mistakes: Json;
          character_stats: Json;
          word_stats: Json;
          completed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          practice_mode: string;
          duration: number;
          final_wpm: number;
          final_accuracy: number;
          consistency: number;
          peak_wpm: number;
          average_wpm: number;
          raw_wpm: number;
          correct_chars: number;
          incorrect_chars: number;
          total_chars: number;
          mistakes?: Json;
          character_stats?: Json;
          word_stats?: Json;
          completed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          practice_mode?: string;
          duration?: number;
          final_wpm?: number;
          final_accuracy?: number;
          consistency?: number;
          peak_wpm?: number;
          average_wpm?: number;
          raw_wpm?: number;
          correct_chars?: number;
          incorrect_chars?: number;
          total_chars?: number;
          mistakes?: Json;
          character_stats?: Json;
          word_stats?: Json;
          completed_at?: string;
          created_at?: string;
        };
      };
      practice_preferences: {
        Row: {
          user_id: string;
          practice_mode: string;
          timer_mode: string;
          duration: number;
          include_punctuation: boolean;
          include_numbers: boolean;
          include_capitalization: boolean;
          word_count: number;
          allow_backspace: boolean;
          blind_mode: boolean;
          strict_mode: boolean;
          font_size: string;
          font_family: string;
          cursor_style: string;
          show_live_wpm: boolean;
          show_keyboard: boolean;
          keyboard_layout: string;
          sound_enabled: boolean;
          reduced_motion: boolean;
          high_contrast: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          practice_mode?: string;
          timer_mode?: string;
          duration?: number;
          include_punctuation?: boolean;
          include_numbers?: boolean;
          include_capitalization?: boolean;
          word_count?: number;
          allow_backspace?: boolean;
          blind_mode?: boolean;
          strict_mode?: boolean;
          font_size?: string;
          font_family?: string;
          cursor_style?: string;
          show_live_wpm?: boolean;
          show_keyboard?: boolean;
          keyboard_layout?: string;
          sound_enabled?: boolean;
          reduced_motion?: boolean;
          high_contrast?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          practice_mode?: string;
          timer_mode?: string;
          duration?: number;
          include_punctuation?: boolean;
          include_numbers?: boolean;
          include_capitalization?: boolean;
          word_count?: number;
          allow_backspace?: boolean;
          blind_mode?: boolean;
          strict_mode?: boolean;
          font_size?: string;
          font_family?: string;
          cursor_style?: string;
          show_live_wpm?: boolean;
          show_keyboard?: boolean;
          keyboard_layout?: string;
          sound_enabled?: boolean;
          reduced_motion?: boolean;
          high_contrast?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      practice_heatmap: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          sessions: number;
          minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          sessions?: number;
          minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          sessions?: number;
          minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      coding_sessions: {
        Row: {
          id: string;
          user_id: string;
          session_id: string;
          session_timestamp: string;
          duration: number;
          mode: string;
          completed: boolean;
          language: string;
          framework: string | null;
          category: string | null;
          snippet_id: string;
          difficulty: string;
          wpm: number;
          raw_wpm: number;
          accuracy: number;
          consistency: number;
          correct_lines: number;
          incorrect_lines: number;
          total_lines: number;
          line_accuracy: number;
          bracket_accuracy: number | null;
          indentation_accuracy: number | null;
          symbol_accuracy: number | null;
          mistakes_count: number;
          text_content: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_id: string;
          session_timestamp?: string;
          duration: number;
          mode?: string;
          completed?: boolean;
          language: string;
          framework?: string | null;
          category?: string | null;
          snippet_id: string;
          difficulty: string;
          wpm: number;
          raw_wpm: number;
          accuracy: number;
          consistency?: number;
          correct_lines?: number;
          incorrect_lines?: number;
          total_lines?: number;
          line_accuracy?: number;
          bracket_accuracy?: number | null;
          indentation_accuracy?: number | null;
          symbol_accuracy?: number | null;
          mistakes_count?: number;
          text_content?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_id?: string;
          session_timestamp?: string;
          duration?: number;
          mode?: string;
          completed?: boolean;
          language?: string;
          framework?: string | null;
          category?: string | null;
          snippet_id?: string;
          difficulty?: string;
          wpm?: number;
          raw_wpm?: number;
          accuracy?: number;
          consistency?: number;
          correct_lines?: number;
          incorrect_lines?: number;
          total_lines?: number;
          line_accuracy?: number;
          bracket_accuracy?: number | null;
          indentation_accuracy?: number | null;
          symbol_accuracy?: number | null;
          mistakes_count?: number;
          text_content?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      code_snippets: {
        Row: {
          id: string;
          user_id: string | null;
          title: string;
          description: string | null;
          language: string;
          framework: string | null;
          category: string;
          difficulty: string;
          type: string;
          code: string;
          tags: string[];
          metadata: Json;
          is_public: boolean;
          is_ai_generated: boolean;
          source: string;
          usage_count: number;
          average_wpm: number | null;
          average_accuracy: number | null;
          rating_sum: number;
          rating_count: number;
          average_rating: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          title: string;
          description?: string | null;
          language: string;
          framework?: string | null;
          category: string;
          difficulty: string;
          type: string;
          code: string;
          tags?: string[];
          metadata?: Json;
          is_public?: boolean;
          is_ai_generated?: boolean;
          source?: string;
          usage_count?: number;
          average_wpm?: number | null;
          average_accuracy?: number | null;
          rating_sum?: number;
          rating_count?: number;
          average_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          description?: string | null;
          language?: string;
          framework?: string | null;
          category?: string;
          difficulty?: string;
          type?: string;
          code?: string;
          tags?: string[];
          metadata?: Json;
          is_public?: boolean;
          is_ai_generated?: boolean;
          source?: string;
          usage_count?: number;
          average_wpm?: number | null;
          average_accuracy?: number | null;
          rating_sum?: number;
          rating_count?: number;
          average_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_practice_recommendations: {
        Row: {
          id: string;
          user_id: string;
          recommendation_type: string;
          priority: string;
          status: string;
          title: string;
          description: string;
          reasoning: string | null;
          recommended_mode: string | null;
          recommended_language: string | null;
          recommended_difficulty: string | null;
          recommended_duration: number | null;
          recommended_focus_areas: string[] | null;
          ai_provider: string;
          ai_model: string | null;
          confidence_score: number | null;
          generated_content: Json | null;
          viewed_at: string | null;
          accepted_at: string | null;
          completed_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recommendation_type: string;
          priority?: string;
          status?: string;
          title: string;
          description: string;
          reasoning?: string | null;
          recommended_mode?: string | null;
          recommended_language?: string | null;
          recommended_difficulty?: string | null;
          recommended_duration?: number | null;
          recommended_focus_areas?: string[] | null;
          ai_provider?: string;
          ai_model?: string | null;
          confidence_score?: number | null;
          generated_content?: Json | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          recommendation_type?: string;
          priority?: string;
          status?: string;
          title?: string;
          description?: string;
          reasoning?: string | null;
          recommended_mode?: string | null;
          recommended_language?: string | null;
          recommended_difficulty?: string | null;
          recommended_duration?: number | null;
          recommended_focus_areas?: string[] | null;
          ai_provider?: string;
          ai_model?: string | null;
          confidence_score?: number | null;
          generated_content?: Json | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_performance_reports: {
        Row: {
          id: string;
          user_id: string;
          report_type: string;
          period_start: string;
          period_end: string;
          title: string;
          summary: string;
          strengths: string[];
          weaknesses: string[];
          improvements: string[];
          recommendations: string[];
          metrics_analyzed: Json;
          typing_insights: Json | null;
          weak_keys: Json | null;
          accuracy_trends: Json | null;
          wpm_trends: Json | null;
          consistency_analysis: Json | null;
          coding_insights: Json | null;
          language_performance: Json | null;
          syntax_mistakes: Json | null;
          framework_proficiency: Json | null;
          practice_frequency_analysis: Json | null;
          best_practice_times: Json | null;
          streak_analysis: Json | null;
          goals_progress: Json | null;
          milestones_reached: string[];
          next_milestones: string[];
          ai_provider: string;
          ai_model: string | null;
          generation_time_ms: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          report_type: string;
          period_start: string;
          period_end: string;
          title: string;
          summary: string;
          strengths?: string[];
          weaknesses?: string[];
          improvements?: string[];
          recommendations?: string[];
          metrics_analyzed: Json;
          typing_insights?: Json | null;
          weak_keys?: Json | null;
          accuracy_trends?: Json | null;
          wpm_trends?: Json | null;
          consistency_analysis?: Json | null;
          coding_insights?: Json | null;
          language_performance?: Json | null;
          syntax_mistakes?: Json | null;
          framework_proficiency?: Json | null;
          practice_frequency_analysis?: Json | null;
          best_practice_times?: Json | null;
          streak_analysis?: Json | null;
          goals_progress?: Json | null;
          milestones_reached?: string[];
          next_milestones?: string[];
          ai_provider?: string;
          ai_model?: string | null;
          generation_time_ms?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          report_type?: string;
          period_start?: string;
          period_end?: string;
          title?: string;
          summary?: string;
          strengths?: string[];
          weaknesses?: string[];
          improvements?: string[];
          recommendations?: string[];
          metrics_analyzed?: Json;
          typing_insights?: Json | null;
          weak_keys?: Json | null;
          accuracy_trends?: Json | null;
          wpm_trends?: Json | null;
          consistency_analysis?: Json | null;
          coding_insights?: Json | null;
          language_performance?: Json | null;
          syntax_mistakes?: Json | null;
          framework_proficiency?: Json | null;
          practice_frequency_analysis?: Json | null;
          best_practice_times?: Json | null;
          streak_analysis?: Json | null;
          goals_progress?: Json | null;
          milestones_reached?: string[];
          next_milestones?: string[];
          ai_provider?: string;
          ai_model?: string | null;
          generation_time_ms?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_generated_lessons: {
        Row: {
          id: string;
          user_id: string;
          lesson_type: string;
          title: string;
          description: string | null;
          difficulty: string;
          target_skills: string[];
          target_weaknesses: string[] | null;
          content: string;
          language: string | null;
          framework: string | null;
          estimated_duration: number | null;
          practice_config: Json | null;
          usage_count: number;
          completion_count: number;
          average_score: number | null;
          is_favorited: boolean;
          user_rating: number | null;
          user_feedback: string | null;
          ai_provider: string;
          ai_model: string | null;
          generation_prompt: string | null;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_type: string;
          title: string;
          description?: string | null;
          difficulty: string;
          target_skills: string[];
          target_weaknesses?: string[] | null;
          content: string;
          language?: string | null;
          framework?: string | null;
          estimated_duration?: number | null;
          practice_config?: Json | null;
          usage_count?: number;
          completion_count?: number;
          average_score?: number | null;
          is_favorited?: boolean;
          user_rating?: number | null;
          user_feedback?: string | null;
          ai_provider?: string;
          ai_model?: string | null;
          generation_prompt?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_type?: string;
          title?: string;
          description?: string | null;
          difficulty?: string;
          target_skills?: string[];
          target_weaknesses?: string[] | null;
          content?: string;
          language?: string | null;
          framework?: string | null;
          estimated_duration?: number | null;
          practice_config?: Json | null;
          usage_count?: number;
          completion_count?: number;
          average_score?: number | null;
          is_favorited?: boolean;
          user_rating?: number | null;
          user_feedback?: string | null;
          ai_provider?: string;
          ai_model?: string | null;
          generation_prompt?: string | null;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_insights_cache: {
        Row: {
          id: string;
          user_id: string;
          insight_type: string;
          cache_key: string;
          insight_data: Json;
          ai_provider: string;
          computed_at: string;
          expires_at: string;
          access_count: number;
          last_accessed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          insight_type: string;
          cache_key: string;
          insight_data: Json;
          ai_provider?: string;
          computed_at?: string;
          expires_at: string;
          access_count?: number;
          last_accessed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          insight_type?: string;
          cache_key?: string;
          insight_data?: Json;
          ai_provider?: string;
          computed_at?: string;
          expires_at?: string;
          access_count?: number;
          last_accessed_at?: string | null;
          created_at?: string;
        };
      };
      ai_user_goals: {
        Row: {
          id: string;
          user_id: string;
          goal_type: string;
          category: string;
          title: string;
          description: string | null;
          target_metric: string;
          target_value: number;
          current_value: number | null;
          start_date: string;
          target_date: string;
          status: string;
          progress_percentage: number | null;
          is_ai_recommended: boolean;
          ai_confidence: number | null;
          recommendation_reasoning: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          goal_type: string;
          category: string;
          title: string;
          description?: string | null;
          target_metric: string;
          target_value: number;
          current_value?: number | null;
          start_date: string;
          target_date: string;
          status?: string;
          progress_percentage?: number | null;
          is_ai_recommended?: boolean;
          ai_confidence?: number | null;
          recommendation_reasoning?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          goal_type?: string;
          category?: string;
          title?: string;
          description?: string | null;
          target_metric?: string;
          target_value?: number;
          current_value?: number | null;
          start_date?: string;
          target_date?: string;
          status?: string;
          progress_percentage?: number | null;
          is_ai_recommended?: boolean;
          ai_confidence?: number | null;
          recommendation_reasoning?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_user_preferences: {
        Row: {
          user_id: string;
          ai_enabled: boolean;
          auto_recommendations: boolean;
          weekly_reports: boolean;
          daily_practice_planner: boolean;
          notification_recommendations: boolean;
          notification_reports: boolean;
          notification_goals: boolean;
          notification_insights: boolean;
          preferred_learning_style: string | null;
          focus_areas: string[];
          avoid_topics: string[];
          preferred_practice_times: string[];
          preferred_languages: string[];
          preferred_difficulty: string | null;
          allow_performance_analysis: boolean;
          allow_habit_tracking: boolean;
          share_insights_anonymous: boolean;
          preferred_ai_provider: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          ai_enabled?: boolean;
          auto_recommendations?: boolean;
          weekly_reports?: boolean;
          daily_practice_planner?: boolean;
          notification_recommendations?: boolean;
          notification_reports?: boolean;
          notification_goals?: boolean;
          notification_insights?: boolean;
          preferred_learning_style?: string | null;
          focus_areas?: string[];
          avoid_topics?: string[];
          preferred_practice_times?: string[];
          preferred_languages?: string[];
          preferred_difficulty?: string | null;
          allow_performance_analysis?: boolean;
          allow_habit_tracking?: boolean;
          share_insights_anonymous?: boolean;
          preferred_ai_provider?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          ai_enabled?: boolean;
          auto_recommendations?: boolean;
          weekly_reports?: boolean;
          daily_practice_planner?: boolean;
          notification_recommendations?: boolean;
          notification_reports?: boolean;
          notification_goals?: boolean;
          notification_insights?: boolean;
          preferred_learning_style?: string | null;
          focus_areas?: string[];
          avoid_topics?: string[];
          preferred_practice_times?: string[];
          preferred_languages?: string[];
          preferred_difficulty?: string | null;
          allow_performance_analysis?: boolean;
          allow_habit_tracking?: boolean;
          share_insights_anonymous?: boolean;
          preferred_ai_provider?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
